# This is a GitHub Actions template for a basic integration with Arm Virtual Hardware

# Requires AVH_TOKEN to be set in repository secret. You can find your token at https://app.avh.arm.com/profile/api

name: Arm Virtual Hardware template
on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  AVH_TOKEN: ${{ secrets.AVH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup the builder
        run: |
          sudo apt install gcc-arm-none-eabi
          # Insert any application or platform specific setup steps here

      - name: Pull the codebase
        uses: actions/checkout@v3

      - name: Build the application
        run: |
          cd src/STM32/IOT_HTTP_WebServer/STM32CubeIDE/Debug
          make -j all

      - name: Build the application image
        run: |
          arm-none-eabi-objcopy -O binary src/STM32/IOT_HTTP_WebServer/STM32CubeIDE/Debug/IOT_HTTP_WebServer.elf src/STM32/IOT_HTTP_WebServer/STM32CubeIDE/Debug/IOT_HTTP_WebServer.bin

      - name: Upload the application image
        uses: actions/upload-artifact@v3
        with:
          name: IOT_HTTP_WebServer.bin
          path: src/STM32/IOT_HTTP_WebServer/STM32CubeIDE/Debug/IOT_HTTP_WebServer.bin

  run-test-avh:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install the dependencies
        run: |
          pip3 install avh-api avh-api-async websockets python-dateutil aiohttp six urllib3

      - name: Download the code base
        uses: actions/checkout@v3

      - name: Download the application image
        uses: actions/download-artifact@v3
        with:
          name: IOT_HTTP_WebServer.bin
          path: ${{ github.workspace }}
